### ISSUE TITLE
Polish Task View

### ISSUE THREAD

**Issue by sauterl** [lucaro/DRES#25]
- [x] Visual KIS Task: Show Keyframe of Submission
- [x] Textual KIS Task: Show Shot **after** Timeout
- [x] Textual KIS Task: Show Placeholder per Submission

**Comment by ppanopticon** [comment]
**TODO:** Determine in _backend_ whether MediaItem should be sent to client when Submissions are queried. This will determine, whether or not a keyframe is displayed!

**Comment by lucaro** [comment]
In what situation would you have a submission whthout media item?

**Comment by ppanopticon** [comment]
I thought we discussed last time that the backend would decide, whether or not to display the thumbnail associated with the submission and that this would be signaled by presence or absence of the MediaItem.

But maybe I'm confusing something her. In any case, however, we'll require some cue as to whether the preview should be displayed or not.

**Comment by sauterl** [comment]
I agree, @ppanopticon we did decide last time to manage the display of media items that way.

**Comment by lucaro** [comment]
This has already been implemented in https://github.com/lucaro/DRES/commit/cda41408bb05c745273d538b446e963afa958774. If the media item in a `SubmissionInfo` is not set, it is not supposed to be displayed, otherwise it is.

**Comment by ppanopticon** [comment]
Yes - sorry for the confusion. 

The stubs weren't generated correctly because the Open API annotation still declared _Submission_ instead of _SubmissionInfo_ as return type. It works properly now!
